ci: replace the get-latest-release action with github cli

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,7 +19,8 @@ jobs:
   build:
     name: Build app
     runs-on: 'ubuntu-24.04'
-
+    env:
+      TAG_NAME: ''
     steps:
       - name: Clone Repository (Latest)
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -57,14 +58,28 @@ jobs:
           keyPassword: ${{ secrets.KEY_PASSWORD }}
         env:
           BUILD_TOOLS_VERSION: '35.0.1'
-
-      - name: Get previous release
-        id: last_release
-        uses: InsonusK/get-latest-release@7a9ff16c8c6b7ead5d71c0f1cc61f2703170eade # v1.1.0
+      
+      - name: Clone Preview Repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
-          myToken: ${{ github.token }}
-          exclude_types: 'draft|prerelease'
-          view_top: 1
+          repository: 'mihonapp/mihon-preview'
+          fetch-depth: 0
+          path: 'preview'
+          
+      - name: Get previous release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Get the latest release tag from the preview repository
+          cd preview
+
+          if OUTPUT=$(gh release list --exclude-drafts --exclude-pre-releases --json tagName --limit 1 --jq '.[0].tagName'); then
+            echo "TAG_NAME=$OUTPUT" >> $GITHUB_ENV
+            echo "Latest Tag: $OUTPUT"
+          else
+            echo "Failed to get repository information"
+            exit 1
+          fi
 
       - name: Prepare changelog
         run: |
@@ -75,7 +90,7 @@ jobs:
           current_sha=$(git rev-parse --short HEAD)
           echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV
 
-          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
+          prev_commit_count=$(echo "${{ env.TAG_NAME }}" | sed -e "s/^r//")
           commit_count_diff=$(expr $commit_count - $prev_commit_count)
           prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
           echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV
